CREATE TABLE yaourt_history (
    id BIGINT generated by default as identity (start with 1),
    user_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id)
);

CREATE TABLE user_config (
    id BIGINT generated by default as identity (start with 1),
    user_id BIGINT NOT NULL,
    delivery_time INTEGER NOT NULL,
    monday_consommation INTEGER NOT NULL,
    tuesday_consommation INTEGER NOT NULL,
    wednesday_consommation INTEGER NOT NULL,
    thursday_consommation INTEGER NOT NULL,
    friday_consommation INTEGER NOT NULL,
    saturday_consommation INTEGER NOT NULL,
    sunday_consommation INTEGER NOT NULL,
    yaourt_format integer not null,

    primary key (id)
);